[project]
name = 'Randomized-Rewards-System'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.randomized-rewards]
path = 'contracts/randomized-rewards.clar'
clarity_version = 2
epoch = 2.5

[contracts.utils]
path = 'contracts/utils.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
